### ISSUE TITLE
Apologies in Advance

### ISSUE THREAD

**Issue by thoward27** [chinmaypantdev/qodis#17]
This is not a real issue. I have found no bugs in your software.

I am writing this to ask if you had any idea how to get sveltekit + gun deployed to netlify. I see your app runs on heroku, no worries if you don't have any clues for me. But I'm trying to get this PR to fly: https://github.com/thoward27/thor/pull/2, nothing I do is working.

In any event, if you're too busy or whatever, feel free to just close this :) 

Have a good one!

**Comment by chinmaypantdev** [comment]
> I see your app runs on heroku, no worries if you don't have any clues for me. But I'm trying to get this PR to fly: thoward27/thor#2, nothing I do is working.

Initially I was planning to use Netlify, mainly because the ease of use and the support of HTTP/2 that [increases the performance](https://web.dev/uses-http2).

When I actually tried deploying this app on Netlify using [the official adapter](https://github.com/sveltejs/kit/tree/master/packages/adapter-netlify), some random errors, related to dependencies were being returned. When I tried installing missing dependencies, the weird internal errors were coming.

I am not really expert in SvelteKit and was just learning it through this project, so I didn't really went deeper into the problem. But it was clear that the errors were related to GunJS as deploying other sites made with SvelteKit without GunJS on Netlify were not giving those errors.

I did all above mentioned steps using Vercel, and the results were same.

So finally I decided to use [Node Adapter](https://github.com/sveltejs/kit/tree/master/packages/adapter-node) and run the [PolkaJS](https://github.com/lukeed/polka) server on Heroku app to serve the app and it didn't give me those weird errors. And that is the reason I am using Heroku (without any desire to use it) for this project.

> I am writing this to ask if you had any idea how to get sveltekit + gun deployed to netlify.

Sorry, I really don't have any ideas to deploy the SvelteKit app with GunJS on Netlify (or Vercel).
